name: Deploy to Vercel (Pure CLI)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      CI: "true"
      VERCEL_FORCE: "true"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 安装最新 Vercel CLI（v34+，2025 年版本）
      - name: Install Latest Vercel CLI
        run: |
          npm install -g vercel@latest --silent
          vercel --version

      # 纯 CLI 部署：强制非交互
      - name: Deploy to Production
        run: |
          # 自动创建/链接项目
          vercel link --yes --prod --force || true
          
          # 强制部署
          DEPLOY_URL=$(vercel --prod --yes --force --confirm 2>/dev/null | grep -o 'https://[^ ]*\.vercel\.app' | head -1)
          
          if [ -n "$DEPLOY_URL" ]; then
            echo "部署成功！访问：$DEPLOY_URL"
            echo "URL=$DEPLOY_URL" >> $GITHUB_OUTPUT
          else
            echo "部署完成，请在 Vercel 仪表板查看"
          fi
