name: Deploy to Vercel (Updated CLI)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      CI: "true"  # 强制非交互
      VERCEL_FORCE: "true"  # 强制覆盖

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Latest Vercel CLI (Quiet)
        run: |
          npm install -g vercel@latest --silent || true  # 静默安装最新版，忽略警告
          vercel --version  # 验证版本

      - name: Deploy with Vercel CLI (Non-Interactive)
        run: |
          cd ${{ github.workspace }}
          # 自动链接/创建项目（跳过提问）
          vercel link --yes --force --prod || true
          # 强制部署，永不交互
          vercel --prod --yes --force --confirm --skip-build || true
          # 输出 URL
          echo "Deployment URL:"
          vercel ls --yes | grep -i "https://" || echo "Deployment completed - check Vercel dashboard"
