name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 使用最新 vercel-action@v32 + 强制非交互
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v32
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod --yes --force'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}     # 可选
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # 可选
          working-directory: .
